/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/base/icon/BaseIcon.vue')['default']
    BasePopup: typeof import('./src/components/base/popup/BasePopup.vue')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
    TheLayout: typeof import('./src/components/layout/TheLayout.vue')['default']
    ThePageLoading: typeof import('./src/components/loading/ThePageLoading.vue')['default']
    TheSidebar: typeof import('./src/components/layout/TheSidebar.vue')['default']
  }
}
